spring.application.name=GestionDeTri

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/GesTri
spring.datasource.username=batcharaoudate
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8081
