package com.raoudate.GestionDeTri.Enum;

public enum permissionName {
    COLIS_CREATE, COLIS_READ, COLIS_UPDATE, COLIS_DELETE,
    AGENCE_CREATE, AGENCE_READ, AGENCE_UPDATE, AGENCE_DELETE,
    UTILISATEUR_READ, UTILISATEUR_CREATE, UTILISATEUR_UPDATE, UTILISATEUR_DELETE
}
