-- Script de mise à jour des codes_bureau pour chaque agence
-- Total: 94 associations code_bureau -> agence
-- Date: 2025-11-18

UPDATE agences SET code_bureau = '01' WHERE label = 'LOME CENTRE';
UPDATE agences SET code_bureau = '200' WHERE label = 'ATAKPAME';
UPDATE agences SET code_bureau = '5' WHERE label = 'LOME AGBALEPEDOGAN';
UPDATE agences SET code_bureau = '260' WHERE label = 'KPALIME';
UPDATE agences SET code_bureau = '400' WHERE label = 'KARA';
UPDATE agences SET code_bureau = '300' WHERE label = 'SOKODE';
UPDATE agences SET code_bureau = '12' WHERE label = 'LOME BAGUIDA';
UPDATE agences SET code_bureau = '04' WHERE label = 'LOME ADIDOGOME';
UPDATE agences SET code_bureau = '18' WHERE label = 'LOME AVEDJI';
UPDATE agences SET code_bureau = '540' WHERE label = 'MANDOURI';
UPDATE agences SET code_bureau = '450' WHERE label = 'KETAO';
UPDATE agences SET code_bureau = '195' WHERE label = 'AFAGNAN';
UPDATE agences SET code_bureau = '290' WHERE label = 'NOTSE';
UPDATE agences SET code_bureau = '230' WHERE label = 'TOHOUN';
UPDATE agences SET code_bureau = '210' WHERE label = 'AMLAME';
UPDATE agences SET code_bureau = '220' WHERE label = 'ANIE';
UPDATE agences SET code_bureau = '420' WHERE label = 'BASSAR';
UPDATE agences SET code_bureau = '460' WHERE label = 'NIAMTOUGOU';
UPDATE agences SET code_bureau = '500' WHERE label = 'DAPAONG';
UPDATE agences SET code_bureau = '530' WHERE label = 'MANGO';
UPDATE agences SET code_bureau = '520' WHERE label = 'CINKASSE';
UPDATE agences SET code_bureau = '08' WHERE label = 'LOME TOKOIN';
UPDATE agences SET code_bureau = '13' WHERE label = 'LOME AGOE-ASSIYEYE';
UPDATE agences SET code_bureau = '11' WHERE label = 'LOME DJIFA-KPOTA';
UPDATE agences SET code_bureau = '130' WHERE label = 'ANEHO';
UPDATE agences SET code_bureau = '160' WHERE label = 'TSEVIE';
UPDATE agences SET code_bureau = '240' WHERE label = 'BADOU';
UPDATE agences SET code_bureau = '29' WHERE label = 'LOME LEGBASSITO';
UPDATE agences SET code_bureau = '235' WHERE label = 'GLEI';
UPDATE agences SET code_bureau = '225' WHERE label = 'ELAVAGNON';
UPDATE agences SET code_bureau = '250' WHERE label = 'AGOU';
UPDATE agences SET code_bureau = '270' WHERE label = 'KPELE-ADETA';
UPDATE agences SET code_bureau = '215' WHERE label = 'DANYI APEYEME';
UPDATE agences SET code_bureau = '280' WHERE label = 'KPELE-ELE';
UPDATE agences SET code_bureau = '330' WHERE label = 'TCHAMBA';
UPDATE agences SET code_bureau = '350' WHERE label = 'KABOLI';
UPDATE agences SET code_bureau = '320' WHERE label = 'SOTOUBOUA';
UPDATE agences SET code_bureau = '310' WHERE label = 'BLITTA';
UPDATE agences SET code_bureau = '360' WHERE label = 'PAGALA';
UPDATE agences SET code_bureau = '370' WHERE label = 'ADJENGRE';
UPDATE agences SET code_bureau = '480' WHERE label = 'PYA';
UPDATE agences SET code_bureau = '410' WHERE label = 'BAFILO';
UPDATE agences SET code_bureau = '470' WHERE label = 'PAGOUDA';
UPDATE agences SET code_bureau = '140' WHERE label = 'ANFOIN';
UPDATE agences SET code_bureau = '110' WHERE label = 'AGBODRAFO';
UPDATE agences SET code_bureau = '120' WHERE label = 'AGBELOUVE';
UPDATE agences SET code_bureau = '150' WHERE label = 'TABLIGBO';
UPDATE agences SET code_bureau = '135' WHERE label = 'AKLAKOU';
UPDATE agences SET code_bureau = '165' WHERE label = 'AHEPE';
UPDATE agences SET code_bureau = '190' WHERE label = 'HAHOTOE';
UPDATE agences SET code_bureau = '180' WHERE label = 'KEVE';
UPDATE agences SET code_bureau = '170' WHERE label = 'VOGAN';
UPDATE agences SET code_bureau = '201' WHERE label = 'AGBONOU';
UPDATE agences SET code_bureau = '202' WHERE label = 'HIHEATRO';
UPDATE agences SET code_bureau = '245' WHERE label = 'KOUGNOHOU';
UPDATE agences SET code_bureau = '301' WHERE label = 'SOKODE KPAGALAM';
UPDATE agences SET code_bureau = '430' WHERE label = 'GUERIN-KOUKA';
UPDATE agences SET code_bureau = '455' WHERE label = 'KABOU';
UPDATE agences SET code_bureau = '440' WHERE label = 'KANTE';
UPDATE agences SET code_bureau = '401' WHERE label = 'KARA STADE';
UPDATE agences SET code_bureau = '510' WHERE label = 'BOMBOUAKA';
UPDATE agences SET code_bureau = '550' WHERE label = 'BARKOISSI';
UPDATE agences SET code_bureau = '631' WHERE label = 'LOME CHEQUES';
UPDATE agences SET code_bureau = '915' WHERE label = 'LOME AGOE FIOVI';
UPDATE agences SET code_bureau = '960' WHERE label = 'LOME LEGBASSITO';
UPDATE agences SET code_bureau = '913' WHERE label = 'LOME AMADAHOME';
UPDATE agences SET code_bureau = '914' WHERE label = 'LOME ADETIKOPE';
UPDATE agences SET code_bureau = '961' WHERE label = 'LOME AVEPOZO';
UPDATE agences SET code_bureau = '962' WHERE label = 'LOME SEGBE';
UPDATE agences SET code_bureau = '963' WHERE label = 'LOME ADAKPAME';
UPDATE agences SET code_bureau = '964' WHERE label = 'LOME ZOSSIME';
UPDATE agences SET code_bureau = '965' WHERE label = 'LOME DJAGBLE';
UPDATE agences SET code_bureau = '966' WHERE label = 'LOME AGOE ADJOUGBA';
UPDATE agences SET code_bureau = '967' WHERE label = 'LOME KPOGAN';
UPDATE agences SET code_bureau = '912' WHERE label = 'LOME ZANGUERA';
UPDATE agences SET code_bureau = '916' WHERE label = 'LOME NOEPE';
UPDATE agences SET code_bureau = '922' WHERE label = 'ASRAMA';
UPDATE agences SET code_bureau = '924' WHERE label = 'AMOU OBLO';
UPDATE agences SET code_bureau = '932' WHERE label = 'DJARKPANGA';
UPDATE agences SET code_bureau = '935' WHERE label = 'KOUSSOUNTOU';
UPDATE agences SET code_bureau = '940' WHERE label = 'SIOU';
UPDATE agences SET code_bureau = '941' WHERE label = 'BAPURE';
UPDATE agences SET code_bureau = '942' WHERE label = 'KOUMEA';
UPDATE agences SET code_bureau = '944' WHERE label = 'ATCHANGBADE';
UPDATE agences SET code_bureau = '945' WHERE label = 'BANGELI';
UPDATE agences SET code_bureau = '950' WHERE label = 'GANDO';

-- Vérification
SELECT COUNT(*) as total_code_bureau_sets FROM agences WHERE code_bureau IS NOT NULL;
SELECT COUNT(*) as total_agences FROM agences;
